name: "CI"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  nix:
    runs-on: ${{ matrix.label }}
    strategy:
      matrix:
        include:
          - system: aarch64-darwin
            label: macOS
          - system: aarch64-linux
            label: Linux
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: packages
        run: nixci build .#packages."${{ matrix.system }}"

      - name: checks
        run: nixci build .#checks."${{ matrix.system }}"

      - name: devShells
        run: nixci build .#devShells."${{ matrix.system }}"

      # First, build the repos used in the test to cache them locally, so as
      # to avoid GitHub rate limits during the integration test (which
      # doesn't use the token)
     # - name: Integration Test (preparation)
     #   run: |
     #     nixci build "github:srid/haskell-multi-nix/c85563721c388629fa9e538a1d97274861bc8321" -- --no-link
     #     nixci build "github:juspay/services-flake/3d764f19d0a121915447641fe49a9b8d02777ff8" -- --no-link
     # - name: Integration Test
     #   run: |
     #     git status
     #     nix develop -c cargo test -F integration_test
